# Generated by Django 4.2.7 on 2023-11-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(max_length=4)),
                ('target_currency', models.CharField(max_length=4)),
                ('amount', models.IntegerField()),
                ('conversion_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=4)),
                ('to_currency', models.CharField(max_length=4)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
