# Generated by Django 4.2.7 on 2023-11-11 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_permanent', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ConversionHistory',
        ),
        migrations.AddField(
            model_name='conversionrate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conversionrate',
            name='from_currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='conversionrate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='conversionrate',
            name='to_currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AddField(
            model_name='conversion',
            name='conversion_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversion.conversionrate'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
