# Generated by Django 4.2.7 on 2023-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversion',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
    ]
