# Generated by Django 4.2.7 on 2023-11-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_alter_currencyconversion_conversion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconversion',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
