# Generated by Django 4.2.7 on 2023-11-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0003_alter_currencyconversion_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversionRate',
        ),
    ]
